apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhands-app
  namespace: openhands
  labels:
    app: openhands-app
spec:
  rules:
  - host: openhands.site.tld
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openhands-app
            port:
              number: 3000
