apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openhands
  name: runtime-api-sa
  labels:
    helm.sh/chart: runtime-api-0.1.20
    app.kubernetes.io/name: runtime-api
    app.kubernetes.io/instance: openhands
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
