apiVersion: v1
kind: Service
metadata:
  namespace: openhands
  name: openhands-redis-headless
  labels:
    app.kubernetes.io/instance: openhands
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.1
    helm.sh/chart: redis-20.3.0
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/instance: openhands
    app.kubernetes.io/name: redis
