apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  namespace: openhands
  name: openhands-redis-master
  labels:
    app.kubernetes.io/instance: openhands
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.1
    helm.sh/chart: redis-20.3.0
