apiVersion: v1
kind: Service
metadata:
  namespace: openhands
  name: openhands-service
  labels:
    app: openhands
spec:
  ports:
  - name: openhands
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: openhands
  type: ClusterIP
