apiVersion: v1
kind: Service
metadata:
  namespace: openhands
  name: oh-main-runtime-api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: runtime-api
    app.kubernetes.io/instance: openhands
